name: smbrl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=2.119
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.1.4
  - cuda-cccl=12.3.52
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.52
  - cuda-opencl-dev=12.3.52
  - cuda-profiler-api=12.3.52
  - cuda-runtime=12.1.0
  - debugpy=1.8.0
  - decorator=5.1.1
  - executing=2.0.1
  - filelock=3.13.1
  - freetype=2.12.1
  - idna=3.4
  - importlib_metadata=6.8.0
  - intel-openmp=2023.2.0
  - ipykernel=6.26.0
  - ipython=8.12.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.4.52
  - libcurand-dev=10.3.4.52
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.19
  - libffi=3.4.2
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.44.0
  - libtiff=4.6.0
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mkl=2023.2.0
  - mkl-devel=2023.2.0
  - mkl-include=2023.2.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - nest-asyncio=1.5.8
  - numpy=1.24.4
  - openjpeg=2.5.0
  - openssl=3.1.4
  - packaging=23.2
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pip=23.3.1
  - platformdirs=3.11.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pygments=2.16.1
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pywin32=306
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - requests=2.31.0
  - six=1.16.0
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.10.0
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.13.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - ucrt=10.0.22621.0
  - urllib3=2.0.7
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wcwidth=0.2.9
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - ale-py==0.7.4
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - cachetools==5.3.2
      - certifi==2023.7.22
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.44.0
      - fsspec==2023.10.0
      - google-auth==2.23.4
      - google-auth-oauthlib==1.0.0
      - grpcio==1.59.2
      - gym==0.21.0
      - gym-retro==0.8.0
      - gym-super-mario-bros==7.3.0
      - importlib-metadata==4.13.0
      - importlib-resources==6.1.1
      - kiwisolver==1.4.5
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - matplotlib==3.7.3
      - mdurl==0.1.2
      - nes-py==8.2.1
      - networkx==3.1
      - oauthlib==3.2.2
      - opencv-python==4.8.1.78
      - pandas==2.0.3
      - protobuf==4.25.0
      - psutil==5.9.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyglet==1.5.21
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - requests-oauthlib==1.3.1
      - rich==13.6.0
      - rsa==4.9
      - setuptools==65.5.0
      - stable-baselines3==1.8.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - torch==2.1.0
      - torchaudio==2.1.0
      - torchvision==0.16.0
      - tqdm==4.66.1
      - tzdata==2023.3
      - werkzeug==3.0.1
      - wheel==0.38.4